
- hosts: fate
  name: Uninstall Eggroll Server
  any_errors_fatal: True
  gather_facts: no
  vars_files:
  - var_files/prod/base_init
  - var_files/prod/fate_init
  tasks:
  - name: Stop clustermanager service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-clustermanager
    ignore_errors: yes

  - name: Stop nodemanager service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-nodemanager
    ignore_errors: yes

  - name: Stop rollsite service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-rollsite
    ignore_errors: yes

  - name: Remove eggroll deployfiles
    file: path={{item}} state=absent
    with_items:
    - "{{pbase}}/{{pname}}/eggroll"

  - name: Remove eggroll datafiles
    file: path={{item}} state=absent
    with_items:
    - "{{dbase}}/{{pname}}/eggroll"
    - "{{dbase}}/{{pname}}/keys"

  - name: Remove supervisord files
    file: path={{item}} state=absent
    with_items:
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-clustermanager.conf"
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-nodemanager.conf"
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-rollsite.conf"
