
- hosts: fate
  name: Uninstall fate_flow Server
  any_errors_fatal: True
  gather_facts: no
  vars_files:
  - var_files/prod/base_init
  - var_files/prod/fate_init
  tasks:
  - name: Stop fate_flow service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-fateflow
    ignore_errors: yes

  - name: Remove fate_flow deployfiles
    file: path={{item}} state=absent
    with_items:
    - "{{pbase}}/{{pname}}/python"
    - "{{pbase}}/{{pname}}/examples"
    - "{{pbase}}/{{pname}}/bin"
    - "{{pbase}}/{{pname}}/conf"
    - "{{pbase}}/{{pname}}/logs"
    - "{{pbase}}/{{pname}}/fate.env"
    - "{{pbase}}/{{pname}}/RELEASE.md"
    - "{{pbase}}/{{pname}}/{{python['venv']}}"

  - name: Remove supervisord files
    file: path={{item}} state=absent
    with_items:
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-fateflow.conf"
