
- hosts: fate
  name: Uninstall fateboard Server
  any_errors_fatal: True
  gather_facts: no
  vars_files:
  - var_files/prod/base_init
  - var_files/prod/fate_init
  tasks:
  - name: Stop fateboard service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-fateboard
    ignore_errors: yes

  - name: Remove fateboard deployfiles
    file: path={{item}} state=absent
    with_items:
    - "{{pbase}}/{{pname}}/fateboard"

  - name: Remove supervisord files
    file: path={{item}} state=absent
    with_items:
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-fateboard.conf"
