
- hosts: fate
  name: Uninstall Mysql Server
  any_errors_fatal: True
  gather_facts: no
  vars_files:
  - var_files/prod/base_init
  - var_files/prod/fate_init
  tasks:
  - name: Stop mysql service
    shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-mysql
    ignore_errors: yes

  - name: Remove mysql deployfiles
    file: path={{item}} state=absent
    with_items:
    - "{{pbase}}/{{pname}}/{{mysql['path']}}"

  - name: Remove mysql datafiles
    file: path={{item}} state=absent
    with_items:
    - "{{pbase}}/data/{{pname}}/mysql"

  - name: Remove supervisord files
    file: path={{item}} state=absent
    with_items:
    - "{{cbase}}/supervisord/supervisord.d/{{pname}}-mysql.conf"
